// <auto-generated />
namespace StoreSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addproductDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addproductDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202304080818399_addproductDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
